version: "3"
services:
  pfp-container:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: "4"
    ports:
      - "8888:8888" # jupyter
    volumes:
      - ./pfp_docker/logs/system:/var/log/
      - ./scripts:/opt/pfp/scripts/ # remove after development
      - ./pfp_docker/local:/opt/pfp/pfp/
      - ./examples:/opt/pfp/examples/ # remove after development
      - ./env_gpu.yaml:/opt/pfp/env_gpu.yaml # remove after development
      - type: bind
        source: ./polyfingerprints
        target: /tmp/packages/polyfingerprints
        read_only: true
    environment:
      - JUPYTER_TOKEN=pfppassword

    # uncomment to use GPU
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          capabilities: [gpu]
